var rawSpeakers = {
  "pdx": [
    {
      "name": "Sam Handler",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Sam Handler is a Staff Engineer at Shopify and a contributor to several OpenTelemetry repositories. Over the past 12 years, he’s worked on (almost!) every layer of the stack from CSS to iptables. He’s worked towards greater government transparency at the Sunlight Foundation, helped advance infrastructure as code at Hashicorp, and consulted with a wide variety of companies during that time.",
      "title": "OpenResty, My Bestie: Tracing NGINX With Lua",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "c21f4a4939e85f70998409b445e9db2b",
    },
    {
      "name": "Emily Nakashima",
      "pronouns": "She/Her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Emily is VP of Engineering at observability startup Honeycomb. A developer tools nerd, she previously worked at Bugsnag and GitHub, and is passionate about building best-in-class, consumer-quality tools for engineers. She has a background in product engineering, performance optimization, client-side monitoring, and design. In her spare time, she advocates for affordable housing and thinks a lot about disaster preparedness.",
      "title": "Building a real-time cloud cost management program with observability",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "187b1d0ce8cbf89fe3391f6be6fa9799",
    },
    {
      "name": "Adriana Villela",
      "pronouns": "She/Her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Adriana Villela is a Sr. Developer Advocate at Lightstep, in Toronto, Canada, with over 20 years of experience in technology. She focuses on helping companies achieve reliability greatness by leveraging Observability, SRE, and DevOps practices. Before Lightstep, she was a Sr. Manager at Tucows, running both a Platform Engineering team, and an Observability Practices team. Adriana has also worked at various large-scale enterprises, in both individual contributor and leadership roles, including Bank of Montreal, Ceridian, and Accenture. Adriana has a popular technical blog on Medium, is an OpenTelemetry contributor, HashiCorp Ambassador, and co-host of the On-Call Me Maybe Podcast.",
      "title": "Observability Anti-Patterns",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "b039d11030d001023259eea68551eb8d",
    },
    {
      "name": "Leon Adato",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "In my sordid career, I've worked as an actor, bug exterminator, wild-animal remover, electrician, carpenter, stage-combat instructor, American Sign Language interpreter, and Sunday school teacher. Oh, and with computers. Since 1989 (when you got a free copy of Windows 286 on twelve 5¼” floppies when you bought a copy of Excel 1.0). In IT, I've had jobs as a classroom instructor, courseware designer, desktop support tech, server support engineer, and software distribution expert. Then about 20 years ago I got involved with monitoring, working with a wide range of tools: Tivoli, Nagios, Patrol, ZenOss, OpenView, SiteScope, SolarWinds, and New Relic. In the course of that work, I've designed solutions for companies that ranged in size from modest (~10 systems); to middle of the road (1,000 - 5,000 systems); to ludicrously large (250,000 systems in 5,000 locations).",
      "title": "Alerts Don't Suck. YOUR Alerts Suck!",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "8c2f10637f21718b0216aa597bdd19ef",
    },
    {
      "name": "Mandy Riso",
      "pronouns": "She/Her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Mandy is a Reliability Engineering Manager at Stack Overflow.  She is neurodivergent and loves to learn more on how that impacts everyday situations.  She lives in the PNW with her family and loves the great outdoors.",
      "title": "Dyslexia - How I Fumbled My Way Through Tech (and What You Can Do To Help)",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "63d0e823f0df3b4d448c12c16f080807",
    },
    {
      "name": "Brooke Sargent",
      "pronouns": "She/Her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Brooke is currently a software engineer at Honeycomb building APIs and integrations with other tools in the developer ecosystem. Her previous experience includes headless e-commerce, IoT, and engineering management. In her spare time, she can be found in the kitchen on a quest to master baking the perfect pie.",
      "title": "Foster a Culture of Learning Through Observability",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "57fe8712ac7c8097bbbe5ea719a76dc4",
    },
    {
      "name": "Dan Ravenstone",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Dan Ravenstone, the alter ego of Frank the Virtual Mechanic, aspired to be next great visual artist and skateboarder, but thanks to ADHD, quickly developed a passion for computing. Through that passion discovered the wonderful world of monitoring and more recently observability. For the last 20 years he has made it a priority in his career to enhance, improve, and evangelize monitoring and observability tools, processes, and best practices.",
      "title": "Thinking Critically About Alerting",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "093eec10332c0c0cc62cdae40718c6ff",
    },
    {
      "name": "Mike Cox",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Hallo! I'm an engineer based out of Seattle, WA with a keen interest in getting paged less. I've been shipping software at tech startups for over a decade and am still surprised (and intrigued) by the many novel ways our industry discovers to bring down Prod.  ",
      "title": "Stress, OnCall, and You",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "9753bd62f8d0d2110274058b6e500e2c",
    },
    {
      "name": "David Gildeh",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "David Gildeh leads the Telemetry Engineering team at Netflix, which is responsible for collecting, storing and querying all of Netflix's observability data (metrics, logs, traces). Previously he was founder/CEO of Outlyer (formerly Dataloop.IO), an observability company which was sold in 2019. He has written about time-series databases and OpenTelemetry on his blog: https://www.davidgildeh.com",
      "title": "How to Scale Observability Without Bankrupting the Company",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "5cac500d3d1f719bb1a8316dddf9ea3a",
    },
    {
      "name": "Ben Rockwood",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Ben Rockwood is the VP of Engineer & Operations at Mondoo, an Open Source Extended Posture Management Security company. He's been in the industry since the mid-90s and held positions Equinix, Packet, Chef, Joyent, Sun Microsystems and many more. One of the early DevOps thought leaders, he's a lover of systems thinking, LEAN principles, and building elegant solutions. When he's not operating, securing, developing, auditing, training, speaking, or managing he hides in the forest of Bainbridge Island, WA with his super awesome wife Tamarah and their 5 incredible children.",
      "title": "Custom End to End Monitoring Made Easy with Github Actions & Playwright",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "91bf00351d5885052a106f078d6c547a",
    },
    {
      "name": "Dave McAllister",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Currently providing technical  OSS evangelism for NGINX, Dave talks about the advantages of microservices and orchestration to solve distributed systems challenges, especially with open source. Dave has been a champion for open systems and open source from the early days of Linux to today's world of clouds and containers. He often speaks on topics associated with emerging software architectures and practices, on observability and on how open source innovations power today's world.",
      "title": "Know your data: The stats behind your alerts",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "fe11a540d3f4e92bd55503223fe46e17",
    },
    {
      "name": "Jack Neely",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Jack Neely is the Observability Architect for the Prisma Cloud division of Palo Alto Networks. He has spent more than 10 years doing monitoring and observability work at major universities, small start ups, and household name companies. With this experience, Jack leads the Observability team in Prisma Cloud in deploying a solution that includes both Open Source and proprietary solutions as a unified observability platform. He is also responsible for building up other teams to understand what Observability is, why the Four Golden Signals matter, and the math behind what makes a great SRE. Outside of work, Jack enjoys singing tenor with the NC Master Chorale and various other choirs around North Carolina.",
      "title": "Observability Data Engineering: A Story About Math, 4 Golden Signals, and Business Intelligence",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "7679f4599cf47937990d7dc4b0b871af",
    },
    {
      "name": "Adrian Cockcroft",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Adrian is currently a technical advisor, analyst and consultant at OrionX.net - he’s advising Catchpoint, Harness, Ampt and Nubank, and having fun presenting at conferences when he feels like it. He retired from Amazon in 2022, where he was a VP working on open source, sustainability and cloud migrations. Previously at Battery Ventures, Netflix, eBay, Sun Microsystems and Cambridge Consultants Ltd.",
      "title": "A Tale of Two Histograms - it was the best of response times, it was the worst of response times...",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "a9220dff7c6e48a125c747dd2eb74ffe",
    },
    {
      "name": "Ivan Merrill",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Ivan Merrill is Head of Solutions Engineering at Fiberplane, based in Amsterdam. Before joining Fiberplane Ivan spent 15 years in large financial enterprises helping teams understand the power of monitoring and observability, whilst leading large-scale deployments of monitoring tools on rather important banking systems.",
      "title": "If you look like a problem, developers will solve you",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "d9b085d3b827acb6b8010324f756bce9",
    },
    {
      "name": "Dylan Ratcliffe",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Dylan is the Founder & CEO of Overmind, building software that discovers changes in the infrastructure you didn't know you had. Before that he spent 6 years at Puppet, helping people eliminate toil and love their jobs again. He loves complex systems & the people that run them, pugs, motorcycles and beer among other things. If you see him in the halls please come and say hi!",
      "title": "Unknown unknowns and how to know them",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "d1ca6d0d949261822cfaaa33e7ad0075",
    },
    {
      "name": "Lerna Ekmekcioglu",
      "pronouns": "She/Her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Lerna Ekmekcioglu is a Senior Solutions Architect with AWS where she helps Global Financial Services customers build secure, scalable and highly available workloads. She brings over 18 years of platform engineering experience including authentication systems, distributed caching, and multi region deployments using IaC and CI/CD to name a few. In her spare time, she enjoys hiking, sight seeing and backyard astronomy.",
      "title": "Have no fear: Just the math you need to know for monitoring",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "0ef0e61fbb875aaa9f6a1c2e516bb6b9",
    },
    {
      "name": "Cliff Moon",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Cliff Moon has been building monitoring and performance software for a long time. He's previously co-founded both Boundary and Opsee. He built one of the first open source NoSQL databases. Now he leads a data engineering team for performance at LinkedIn. When Cliff isn't herding computers, he's tending to his herd of goats in the woods of western Washington.",
      "title": "Performance Testing Experimentation At Scale",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "c8a7750a333cfb27a1c72aa61b73b763",
    },
    {
      "name": "Timothy Mahoney",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Timothy is a senior systems engineer in the Observability Pipeline team at Ingka Group Digital (IKEA). He is passionate about making complex systems observable and sharing knowledge. The skills he gained monitoring and troubleshooting satellite communications networks in his 16 years as a teleport operations manager led to a career pivot into log analytics and observability. He co-developed a large scale, composable Splunk environment in Google Cloud used at IKEA. Timothy volunteers as an arbiter for the RIPE NCC. Originally from Michigan, he lives in southern Sweden with his wife Linda, son Charlie and dog Piggy Pop.",
      "title": "What we talk about when we talk about Observability Frameworks",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "a6d78951ad991749581dd5df08ed8914",
    },
    {
      "name": "Tony Rippy",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Tony is an industry veteran who has worked at a wide variety of companies across finance, big tech and the startup scene. Over time he has built up expertise in the area of distributed systems, where he is always looking for ways to combat complexity. He is currently a keeper of the bits at Two Sigma, where he works on distributed storage systems.",
      "title": "Have you tried *not* storing all those metrics?",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "5c1fd14ce6e455647e6a6a73f452c5b5",
    },
    {
      "name": "Christian Kreibich",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Christian is the technical lead of the Zeek project. He works at Corelight, where he's a Principal Engineer and leads Open Source development. He previously spent 5 years heading the networking group at Lastline, and prior to that spent 5 years as a research scientist at the International Computer Science Institute in Berkeley. He has served on the advisory board of the Open Information Security Foundation, and holds a PhD from the University of Cambridge's Systems Research Group. He still rides skateboards, which recently earned him a busted rotator cuff.",
      "title": "Meet Zeek, the extensible, scriptable network monitor",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "41d4f1d6c03330175b0d35376945be05",
    },
    {
      "name": "Joseph Ruscio",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Joe is a General Partner at Heavybit, a leading early-stage investor in developer-first cloud infrastructure startups. He was previously a CS PhD dropout turned serial entrepreneur who founded Librato, one of the first cloud-native monitoring startups. He lives in Portland OR and loves talking all things monitoring, observability, and more.",
      "title": "A decade of monitoring. Where we started, how we got here, and where we're headed.",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "a27f3b3caf4dc1976bfe07221b33b332",
    },
    {
      "name": "Dominic Hamon",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Dominic Hamon is a Senior Engineering Manager and the Vice-President of Nivenly Foundation. Dominic’s 20+ years of experience have taken him from Theoretical Physics and Maths research, through AAA video game development with the likes of EA and Lucasarts, to large-scale distributed system development for Twitter and Google. He currently works as a Senior Engineering Manager on the Google Play Console platform team, and has also worked on YouTube, Chrome, and Apache Mesos.",
      "title": "Monitoring Mastodons - A story about Hachyderm",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "0e816d453cc8f5b333da83a93ed1cc8c",
    },
    {
      "name": "Alex Hidalgo",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Alex Hidalgo is the Principal Reliability Advocate at Nobl9 and author of &quot;Implementing Service Level Objectives&quot;. During his career he has developed a deep love for sustainable operations, proper observability, and using SLO data to drive discussions and make decisions. Alex's previous jobs have included IT support, network security, restaurant work, t-shirt design, and hosting game shows at bars. When not sharing his passion for technology with others, you can find him scuba diving or watching Premier League football. He lives in Brooklyn with his partner Jen and a rescue dog named Taco. Alex has a BA in philosophy from Virginia Commonwealth University.",
      "title": "Logs Are Good, Actually",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "5eaeee295206dd5e5005a5c90603b1d4",
    },
    {
      "name": "Rob Richardson",
      "pronouns": "He/Him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Rob Richardson is a software craftsman building web properties in ASP.NET and Node, React and Vue. He’s a Microsoft MVP, published author, frequent speaker at conferences, user groups, and community events, and a diligent teacher and student of high quality software development. You can find this and other talks on https://robrich.org/presentations and follow him on twitter at @rob_rich.",
      "title": "The Science and Art of Building RunBooks",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "f047343611694451fccb3fd03c779de7",
    }
  ],
  "baltimore": [
    /* {
      "name": "Riley Berton",
      "pronouns": "",
      "github": "rileyberton",
      "gitlab": "",
      "twitter": "rileyberton",
      "bio": "Riley is a Principal SRE at Major League Baseball with over 20 years experience in building complex systems. He has worked on time series databases @circonus, real time streaming data @AppNexus, audio and video recognition systems @viggle, and audio/video call logging systems @eventide before finding a home at baseball. In his spare time you can find him on the baseball field playing or at the baseball field watching.",
      "title": "What’s Your Service’s Batting Average?",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "64ea38019d0ab54249b9c1d7fa429db1",
    }, */
  ]
}
