var rawSpeakers = {
  "pdx": [
    {
      "name": "Adrian Cockcroft",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Adrian has been monitoring computers for a long time. In the 1990's he wrote the best selling Sun Performance and Tuning book, and contributed to Sun blueprint books on resource management and capacity planning. He recieved the Michelson Award for lifetime contributions from the Computer Measurement Group, and has keynoted and presented at Monitorama several times. He has advised startups including AppDynamics, Instana, NGINX, Docker, BigPanda, Gremlin, and OpsMX, and facilitated the deal between AWS and Grafana. For the last few years Adrian has been focused on sustainability, and has made a deep dive into measurements around carbon emissions and climate risk. He contributed to the Well Architected Guide to Sustainability, released by AWS in December 2021.",
      "title": "Monitoring Carbon",
      "abstract": "An emerging concern is the measurement and optimization of infrastructure and workloads from a sustainability viewpoint. There are many challenges and some new concepts to consider as we think about energy use, and the embodied carbon of the manufacturing lifecycle of the equipment we use. This talk will introduce these new topics and challenges, as we look forward to monitoring tools adding carbon as a monitoring and optimization metric alongside throughput, latency, utilization, capacity and cost.",
      "video": "",
      "slides": "",
      //"hash": "a9220dff7c6e48a125c747dd2eb74ffe"
      "hide": "true",
      "hash": ""
    },
    {
      "name": "Alex Hidalgo",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Alex Hidalgo is the Principal Reliability Advocate at Nobl9 and author of Implementing Service Level Objectives. During his career he has developed a deep love for sustainable operations, proper observability, and using SLO data to drive discussions and make decisions. Alex's previous jobs have included IT support, network security, restaurant work, t-shirt design, and hosting game shows at bars. When not sharing his passion for technology with others, you can find him scuba diving or watching college basketball. He lives in Brooklyn with his partner Jen and a rescue dog named Taco. Alex has a BA in philosophy from Virginia Commonwealth University.",
      "title": "Meaningful Measurements: Lessons from Outside of Tech",
      "abstract": "You need to measure your computer services to know how they're operating. Logs, metrics, traces, SLOs, statistical analysis, probabilistic normalization --  within tech our approaches to understanding how things are going are more complex than ever. But it's not just software and hardware that needs to be monitored. Just about every discipline on the planet has some concept of how to monitor, measure, and account for detected failures. In this talk let's discuss some ways other disciplines measure their own output, and what we can learn from that when measuring our own.",
      "video": "",
      "slides": "",
      "hash": "5eaeee295206dd5e5005a5c90603b1d4"
    },
    {
      "name": "Arda Icmez",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "I've been with Meta(formerly Facebook) for more than 3 years, actively working in Monitoring domain. I've received my Masters Degree from Duke University.",
      "title": "Detection & Alerting at FB: Improving signal to noise ratio at Scale",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "240744aa3580b57222199a1cb72e20f5"
    },
    {
      "name": "Biju Chacko",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "SLOTracker: Tracking SLOs in the real world",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Chris Ward",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Tech writer for Chronosphere. Podcaster, video maker, writer of interactive fiction & games.",
      "title": "Using Grafana to Measure the Impact of Documentation",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "35a44b69ae5c2c1d250216f8ccc9d67c"
    },
    {
      "name": "Clint Sharp",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Clint Sharp has been monitoring and observing systems and networks for over twenty years. For the last ten years, Clint has been making software for processing observability data for most recently as co-founder and CEO of Cribl and previously at Splunk. Prior to being a vendor, Clint ran operations teams responsible for running complex distributed systems at Cricket and AT&T. Running systems is a thankless job, and Clint is passionate about trying to improve operators lives, in some little way, by building great software.",
      "title": "Universal Observability Requires Universal Instrumentation",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e3d83cc09d8705a0ac89d2298d7c925e"
    },
    {
      "name": "Connie-Lynne Villani",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "With degrees in both Electrical Engineering and Theater Management, Connie-Lynne brings 30 years of System Engineering experience to the table, as well as a keen understanding of how to handle drama in the workplace. In addition to founding and managing Fastly's incident management team, Connie-Lynne has worked at Linden Lab, Change.org, and Groupon, but admits that her favorite position was serving as a board member for the Grilled Cheese Invitational, an annual food festival celebrating all things cheesy.",
      "title": "Compassionate Incident Response",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "8215ce26449737a78a426be0738236e6"
    },
    {
      "name": "Corey Quinn",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Corey is the Chief Cloud Economist at The Duckbill Group, where he specializes in helping companies improve their AWS bills by making them smaller and less horrifying. He also hosts the \"Screaming in the Cloud\" and \"AWS Morning Brief\" podcasts; and curates \"Last Week in AWS,\" a weekly newsletter summarizing the latest in AWS news, blogs, and tools, sprinkled with snark and thoughtful analysis in roughly equal measure.",
      "title": "Build vs Buy: The Final Showdown",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "1627fd3033020d65446b69ec2cbdc9c2"
    },
    {
      "name": "Dudi Cohen",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Dudi is Rookout’s VP of R&D. He is passionate about technology, innovation and bringing ideas to life. He has vast experience in cybersecurity and low-level research and development. Out of the office, he tinkers with electronics and IoT devices, and on vacations, he tries to scuba dive as much as possible.",
      "title": "Tracing is dead: How to maximize results with logging and metrics",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "457d27199a3265cdde4a902b997a5932"
    },
    {
      "name": "Fred Moyer",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Fred Moyer is an Observability Engineer for Zendesk, where he likes to apply math to large sets of data. Fred is a recovering Perl and C programmer, and these days likes to hack in Go and is Ruby. He is a 2018 Google dev award winner for his Istio adapter, a 2013 White Camel award winner, Apache Software Foundation member, and has worked in software engineering and reliability roles for the last 18 years. Fred has two young children and now only rides his bike on the trainer in the garage.",
      "title": "SLIs, SLOs, and Error Budgets at Scale",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6278837dcde59999e3dc77d0beb8a0d1"
    },
    {
      "name": "Hakan Koklu",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Hakan is a Software Engineer in the observability team at Lyft. His main focus is building robust, high scale systems that help Lyft users to go where they need to be. He has worked on data problems as a data analyst, data engineer and software engineer at different companies in the last 6 years. Hakan has a PhD in Electrical Engineering from Boston University focused on optical microscopy and electromagnetic optics. In his spare time, he is trying to read fifty books a year and he fantasizes about learning to play a musical instrument.",
      "title": "Building an In-House Alerting System",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "c1ec9daa13994d6178b7fc041168f5dd"
    },
    {
      "name": "Harish Dixit",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Harish Dixit is a Release To Production Engineer at Meta. Harish and team work on reliability and performance evaluation for all of deployed Facebook fleet of servers. Harish leads the efforts to deal with silent data corruptions within Meta infrastructure along with a special focus on compute and memory reliability within the fleet.  Harish has over 20 patent filings across system architecture and communication domains. As part of this talk, Meta will be giving an overview of silent data corruptions, their prevalence in large scale infrastructure with a case study, and efforts to mitigate them at scale. These efforts are also published as “Silent Data Corruptions at Scale” and “Detecting silent data corruptions in the wild” for the curious reader.",
      "title": "Detecting silent errors in the wild",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "22ce448f20449e45830e2d46ee66de2b"
    },
    {
      "name": "Joe Ross",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Joe Ross holds a PhD in mathematics from Columbia University and was a researcher and instructor in pure mathematics. He has given more than 30 talks about his research at conferences and universities throughout the world, and has 12 peer-reviewed publications in mathematics/statistics. Joe has worked as a data scientist for eight years; in his current role at Splunk, he leads the applied research and machine learning efforts for observability.",
      "title": "Approaches to online quantile estimation",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "2c45622ba5e0df7c693b15107d1ef3f5"
    },
    {
      "name": "Jonathan Perry",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Jonathan founded and led Flowmill (now part of Splunk), which developed an eBPF-based Network Performance Monitoring (NPM) solution -- available as OpenTelemetry's NPM collector. Flowmill emerged from Jonathan's PhD research, prior to which he worked on government R&D in high performance computing and cyber-security. He's a bit of a foodie, and enjoys cycling, hiking, and designing systems that let users analyze a lot of data quickly without breaking the bank.",
      "title": "Practical eBPF: How to build service-aware network monitoring",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6a10a31456d47638485a415243938c5e"
    },
    {
      "name": "Joy Scharmen",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Joy has been working with computer networks and systems engineering for 25+ years. She is currently working as the Director of Infrastructure Engineering at StrongDM and having a blast focusing on reliability and scaling. She loves technical leadership and finding human-friendly and human-focused solutions to technical problems.",
      "title": "Starting smart and planning for growth; what I wish I knew",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "8cec5a7ca030ed6c622d44b7b468cd9b"
    },
    {
      "name": "Leon Adato",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "In my sordid career, I have been an actor, bug exterminator and wild-animal remover (nothing crazy like pumas or wildebeasts. Just skunks and raccoons.), electrician, carpenter, stage-combat instructor, American Sign Language interpreter, and Sunday school teacher. Oh, and I work with computers.</br></br>Since 1989 (when Windows 286 came on twelve 5¼” floppies for free with Excel 1.0) I've worked as a classroom instructor, courseware designer, desktop support tech, server support engineer, and software distribution expert.</br></br>Then about 20 years ago I got involved with monitoring. I've worked with a wide range of tools: Tivoli, Nagios, Patrol, ZenOss, OpenView, SiteScope, SolarWinds, and of course New Relic. I've designed solutions for companies that were modest (~10 systems), significant (5,000 systems), and ludicrous (250,000 systems). In that time, I've learned a lot about monitoring and observability in all it's many and splendid forms.",
      "title": "Technical Empathy",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "56ee722af3a0241ea4b70e25aba35357"
    },
    {
      "name": "Matthew Macdonald-Wallace",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Currently heading up the Observability Community within Contino, Matt has a history of helping organizations monitor and track anything from air quality and viticulture to systems with thousands of servers and instances running public cloud platforms.</br></br>Matt’s experience of working with both physical hardware, IoT devices, and cloud platforms has led him to a strange position in the world of Observabilty in which he has been able to monitor servers, serverless, and even farm animals using the same set of Open Source tools - tools that he continues to recommend to Contino's customers.",
      "title": "Automating Deployments to Grafana, Loki, and Prometheus",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "8a3c26150c976bc664501c5befa66dfc"
    },
    {
      "name": "Monika Singh",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Monika works as a Core SRE @Cloudflare. She is passionate about observability, k8s and databases. Outside of work, she tries to keep up to the energy of her toddler.",
      "title": "Building Scalable Logging Infrastructure using ClickHouse",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "999a3d269557e051f43962965cf76ca9"
    },
    {
      "name": "Natalie Serrino",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Natalie Serrino is a Principal Engineer at New Relic working on the Pixie open source project. She focuses on Pixie’s data layer, more specifically, the PxL language, the PxL compiler, and Pixie’s edge query engine for analytics.",
      "title": "Observability is a Data Problem",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e912232d475fb42fa2bdccb223a9aee5"
    },
    {
      "name": "Oleg Zaytsev",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Software engineer at Grafana Labs, working on Mimir squad.",
      "title": "Handling a billion of active series with Grafana Mimir",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "7361e2e8e94b07fc47b579d0222ee5c5"
    },
    {
      "name": "Owen Diehl",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "As a late comer to software with an unorthodox background, I appreciate the hackers, startups, and those _just figuring it out_. Previously, I helped build the small DC startup, _Nutritionix_ and later infrastructure-as-code products at Fugue. These days I work at Grafana Labs on the logging database, Loki. This primarily means building the OSS project and running the Loki SaaS for thousands of tenants across many cloud provider/region pairs. You can recognize me online by my Bulbasaur avatar.",
      "title": "A Rose By Any Other Name: Translating PromQL To Scale",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "229e52b0b90630b14f7beb24f4b756d2"
    },
    {
      "name": "Pradeep Chhetri",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Pradeep is an SRE at Cloudflare where he currently works in Postgres Team. Originally from Nepal, he is now based in Singapore. In his free time, he enjoys travelling.",
      "title": "Building Scalable Logging Infrastructure using ClickHouse",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "dbfe6bba2752980bbd0e2371a549d9be"
    },
    {
      "name": "Sophia Russell",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Sophia Russell is a Staff Engineer at Betterment. After spending many sleepy mornings slinging pastry dough down south, she made her way to the big city and started slinging code. She cares deeply about code quality, naming things, and designing software with empathy. She has a young daughter, Greta, who loves crawling, eating corn on the cob, and yelling very loudly.",
      "title": "The little SLI that could",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "9e26b25f745138e3e025182365437a34"
    },
    {
      "name": "Steve Flanders",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "As Engineering Executive at Splunk, Steve leads Observability “Getting Data In”: the top contributor to the CNCF OpenTelemetry project. Previously, he served as a founding member and Head of Product at Omnition; and Global Engineering Manager for log analytics at VMware. Steve’s background includes business strategy, software development, product management, user experience, and operations management. He uses data-driven decision-making, agile development processes, and teamwork to create innovative and sustainable solutions; and is distinctly passionate about open-source software and democratizing data.",
      "title": "OTel Me How to DIY Observability",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "3f8db521ff879689c0a33a598ec9bb55"
    },
    {
      "name": "Suman Karumuri",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Suman Karumuri is a Sr. Staff Software Engineer and the tech lead for Observability at Slack. Suman Karumuri is an expert in distributed tracing and was a tech lead of Zipkin and a co-author of OpenTracing standard, a Linux Foundation project via the CNCF.</br></br>Previously, Suman Karumuri has spent several years building and operating petabyte scale log search, distributed tracing and metrics systems at Pinterest, Twitter and Amazon. In his spare time, he enjoys board games, hiking and playing with his kids.",
      "title": "KalDB: A k8s native log search platform",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "3d50b5502ffd0346f3047bf2d246da72"
    }
  ],
  "baltimore": [
    /* {
      "name": "Riley Berton",
      "github": "rileyberton",
      "gitlab": "",
      "twitter": "rileyberton",
      "bio": "Riley is a Principal SRE at Major League Baseball with over 20 years experience in building complex systems. He has worked on time series databases @circonus, real time streaming data @AppNexus, audio and video recognition systems @viggle, and audio/video call logging systems @eventide before finding a home at baseball. In his spare time you can find him on the baseball field playing or at the baseball field watching.",
      "title": "What’s Your Service’s Batting Average?",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "64ea38019d0ab54249b9c1d7fa429db1",
    }, */
  ]
}
