var rawSpeakers = {
  "pdx": [
    {
      "name": "Connie-Lynne Villani",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "With degrees in both Electrical Engineering and Theater Management, Connie-Lynne brings 30 years of System Engineering experience to the table, as well as a keen understanding of how to handle drama in the workplace. In addition to founding and managing Fastly's incident management team, Connie-Lynne has worked at Linden Lab, Change.org, and Groupon, but admits that her favorite position was serving as a board member for the Grilled Cheese Invitational, an annual food festival celebrating all things cheesy.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "8215ce26449737a78a426be0738236e6"
    },
    {
      "name": "Joy Scharmen",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Joy fell into a computer career 20+ years ago, and still loves to learn, tinker, and build things. She particularly enjoys building infrastructure focused teams and working across organizations to spread knowledge and understanding. Right now she's in startup life at StrongDM and is having fun making new things work!",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "8cec5a7ca030ed6c622d44b7b468cd9b"
    },
    {
      "name": "Jonathan Perry",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Jonathan Perry was founder and CEO of Flowmill (now Splunk Network Performance Monitoring), an eBPF-based cloud network observability system. Network observability requires collecting, enriching, and analyzing massive amounts of telemetry; Jonathan takes joy in applying his research and expertise to solve practical day-to-day problems faced by infrastructure SREs - to help observe and address the impact of network communication on distributed services.",
      "title": "Practical eBPF: How to build service-aware network monitoring",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6a10a31456d47638485a415243938c5e"
    },
    {
      "name": "Dudi Cohen",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "Tracing is dead: How to maximize results with logging and metrics",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Alex Hidalgo",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Alex Hidalgo is a Site Reliability Engineer and author of the upcoming Implementing Service Level Objectives (O'Reilly Media, September 2020). During his career he has developed a deep love for sustainable operations, proper observability, and using SLO data to drive discussions and make decisions. Alex's previous jobs have included IT support, network security, restaurant work, t-shirt design, and hosting game shows at bars. When not sharing his passion for technology with others, you can find him scuba diving or watching college basketball. He lives in Brooklyn with his partner Jen and a rescue dog named Taco. Alex has a BA in philosophy from Virginia Commonwealth University.",
      "title": "Food for Thought: What Restaurants Can Teach Us About Reliability",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "12a5229a997c3322335ce53f2ba6f02d"
    },
    {
      "name": "Arda Icmez",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "Detection & Alerting at FB: Improving signal to noise ratio at Scale",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Fred Moyer",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Fred is an SRE and the resident SLOgician at Zendesk, where he works to use Error Budgets to deliver best in class reliability for Zendesk's services. Previously he wrangled large scale web systems at Turnitin.com, and earned his Monitoring and Observability wings at Circonus, dealing with large scale time series telemetry implementations. He has two young kids, so he needs more sleep when he's not on the stationary bike in his garage. He likes to hack C, Go, Perl, and Ruby.",
      "title": "SLIs, SLOs, and Error Budgets at Scale",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6278837dcde59999e3dc77d0beb8a0d1"
    },
    {
      "name": "Owen Diehl",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Owen is informally trained and enjoys self directed learning. He currently works at Grafana on the Cortex & Loki teams, specifically on read path performance. Cortex is a Prometheus compatible backend and Loki is a Prometheus inspired approach to log aggregation. Previously he worked for a small startup, Nutritionix, doing primarily web development. After becoming responsible for both application code and operations, he fell in love with declarative tooling & monitoring. Afterwards, he moved to Fugue in order to marry infrastructure as code and functional programming. In his free time, he plays copious amounts of video games at a low skill level, hikes, and laughs at his own jokes. He is recognizable online by his bulbasaur avatars.",
      "title": "A Rose By Any Other Name: Translating PromQL To Scale",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "229e52b0b90630b14f7beb24f4b756d2"
    },
    {
      "name": "Hakan Koklu",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Hakan is a Software Engineer in the observability team at Lyft. His main focus is building robust, high scale systems that help Lyft users to go where they need to be. He has worked on data problems as a data analyst, data engineer and software engineer at different companies in the last 6 years. Hakan has a PhD in Electrical Engineering from Boston University focused on optical microscopy and electromagnetic optics. In his spare time, he is trying to read fifty books a year and he fantasizes about learning to play a musical instrument.",
      "title": "Building an In-House Alerting System",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "c1ec9daa13994d6178b7fc041168f5dd"
    },
    {
      "name": "Joe Ross",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Joe Ross holds a PhD in mathematics from Columbia University and was a researcher and instructor in pure mathematics, most recently at the University of Southern California. He has given more than 30 talks about his research at conferences and universities throughout the world, and has 10 publications in peer-reviewed mathematics/statistics journals. Joe has worked as a data scientist at machine learning/analytics startups for six years; in his current role, he focuses on a variety of time series (anomaly detection, forecasting, correlation) and sampling problems that arise in monitoring.",
      "title": "Approaches to online quantile estimation",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "2c45622ba5e0df7c693b15107d1ef3f5"
    },
    {
      "name": "Adrian Cockcroft",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Adrian Cockcroft has had a long career working at the leading edge of technology, and is fascinated by what happens next. In his new role as VP Sustainability Architecture at Amazon he is developing and sharing best practices for sustainable product architectures, and working with teams across AWS to support their own sustainability programs.",
      "title": "Monitoring for Sustainability",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e896a34f14b98f376519b5ed85d1359c"
    },
    {
      "name": "Chris Ward",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Tech writer for Chronosphgere. Podcaster, video maker, writer of interactive fiction & games.",
      "title": "Using Grafana to Measure the Impact of Documentation",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "35a44b69ae5c2c1d250216f8ccc9d67c"
    },
    {
      "name": "Matt Weaver",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Matt is a technical leader, developer, and cloud engineer working as Director of Platform Engineering at AvidXchange. He is a DevOps geek, and obsessed with enjoyable developer experiences. In his free time Matt enjoys playing beer league hockey, music, and gaming with his wife and 3 boys.",
      "title": "AvidXchange's DevOps Journey: Improving customer experience and delivery acceleration with Observability",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Steve Flanders",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "As Engineering Director at Splunk, Steve leads Observability “Getting Data In”: the top contributor to the CNCF OpenTelemetry project. Previously, he served as a founding member and Head of Product at Omnition; and Global Engineering Manager for log analytics at VMware. Steve’s background includes business strategy, software development, product management, user experience, and operations management. He uses data-driven decision-making, agile development processes, and teamwork to create innovative and sustainable solutions; and is distinctly passionate about open-source software and democratizing data. Steve authors SFlanders.net, a technology-centric weblog, and presents regularly at international conferences including KubeCon and Google Cloud Next.",
      "title": "OTel Me How to DIY Observability",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "9c3544f7874a52c775eea8b8f25363d5"
    },
    {
      "name": "Clint Sharp",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Clint Sharp has been monitoring and observing systems and networks for over twenty years. For the last ten years, Clint has been making software for processing observability data for most recently as co-founder and CEO of Cribl and previously at Splunk. Prior to being a vendor, Clint ran operations teams responsible for running complex distributed systems at Cricket and AT&T. Running systems is a thankless job, and Clint is passionate about trying to improve operators lives, in some little way, by building great software.",
      "title": "Universal Observability Requires Universal Instrumentation",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e3d83cc09d8705a0ac89d2298d7c925e"
    },
    {
      "name": "Pete Cheslock",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Pete is currently the Chief Product Officer of Allma, helping build the first dynamic workflow management company to help companies solve their most painful and complex events with ease.  Pete is a frequent speaker at Monitorama and loves all things related to monitoring, observability, and metrics.  When he's not helping to build startups, he likes to spend his time fulfilling the requirements of a &quot;suburban dad&quot; by smoking meats and tweeting the results.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6f8b01a43eb907d6b473b37724bfc492"
    }
  ],
  "baltimore": [
    /* {
      "name": "Riley Berton",
      "github": "rileyberton",
      "gitlab": "",
      "twitter": "rileyberton",
      "bio": "Riley is a Principal SRE at Major League Baseball with over 20 years experience in building complex systems. He has worked on time series databases @circonus, real time streaming data @AppNexus, audio and video recognition systems @viggle, and audio/video call logging systems @eventide before finding a home at baseball. In his spare time you can find him on the baseball field playing or at the baseball field watching.",
      "title": "What’s Your Service’s Batting Average?",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "64ea38019d0ab54249b9c1d7fa429db1",
    }, */
  ]
}
