var rawSpeakers = [
  /* {
    "name": "",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  } */
  {
    "name": "Logan McDonald",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Mercedes Coyle",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Peter Bailis",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "John Allspaw",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Zach Musgrave",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Angelo Licastro",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Ian Bennett",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Aditya Mukerjee",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Franka Schmidt",
    "github": "",
    "twitter": "",
    "bio": "Franka is an engineer on the platform team at Mapbox, where she spends her time scaling distributed systems on AWS. She organizes coding workshops for women and non-binary people at ClojureBridge, and loves cycling around Berlin.",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Prateek Rungta",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Peter Bourgon",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Aruna Sankaranarayanan",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Dawn Parzych",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Yan Cui",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Andy Domeier",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Tapasweni Pathak",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Kale Stedman",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Kishore Jalleda",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "George Luong",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Dave Cadwallader",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Megan Kanne",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Beth Cornils",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Allan Espinosa",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Jamie Wilkinson",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
]
