var rawSpeakers = [
  /* {
    "name": "",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  } */
  {
    "name": "Logan McDonald",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Aneel Lakhani",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Mercedes Coyle",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Cindy Sridharan",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "Peter Bailis",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
  {
    "name": "John Allspaw",
    "github": "",
    "twitter": "",
    "bio": "",
    "title": "",
    "abstract": "",
    "video": "",
    "slides": "",
    "hash": "",
  },
]
