var speakers = [
  {
    "name": "Inés Sombra",
    "github": "randommood",
    "twitter": "randommood",
    "bio": "Ines Sombra is a Systems Engineer at Fastly, where she spends her time helping the Web go faster. Ines holds an M.S. in Computer Science and an M.S. in Information Management from Washington University in Saint Louis. Being a true Argentine, she has a fondness for steak, fernet, and a pug named Gordo.",
    "abstract": "From zero to Capacity Planning",
    "videos": [],
    "slides": [],
    "hash": "0cdf19a89992c05e9e3ec36fbbc3af87"
  },
  {
    "name": "Brendan Gregg",
    "github": "brendangregg",
    "twitter": "brendangregg",
    "bio": "Brendan Gregg is a senior performance architect at Netflix, where he does large scale computer performance design, analysis, and tuning. He is the author of multiple technical books including <em>Systems Performance</em> published by Prentice Hall, and received the USENIX LISA Award for Outstanding Achievement in System Administration. He was previously a performance lead and kernel engineer at Sun Microsystems, where he developed the ZFS L2ARC and worked on performance. He has also created numerous performance analysis tools, which have been included in multiple operating systems. His recent work includes developing methodologies and visualizations for performance analysis.",
    "abstract": "Netflix Instance Performance Analysis Requirements",
    "videos": [],
    "slides": [],
    "hash": "12c87172a4fbce038281cd2638dbeb29",
  },
  {
    "name": "Camille Fournier",
    "github": "skamille",
    "twitter": "skamille",
    "bio": "Camille Fournier is the CTO of Rent the Runway, where she and her team of 55 (and growing!) engineers are helping to build the world's first rental platform for luxury goods. Prior to Rent the Runway she was a Vice President at Goldman Sachs, specializing in infrastructure systems. In her limited spare time she contributes to the Apache ZooKeeper project as a committer and PMC member, and helps to oversee the Dropwizard web framework.",
    "abstract": "A People's History of Microservices",
    "videos": [],
    "slides": [],
    "hash": "b0050087da18cd0f2efdff3fe637982a"
  },
  {
    "name": "Jeremy Carroll",
    "github": "phobos182",
    "twitter": "jeremy_carroll",
    "bio": "Jeremy is one of the foundational members of the Site Reliability Engineering team at Pinterest. He helps design, build and monitor Pinterest's applications and systems infrastructure that currently handles billions of monthly page views with tremendous growth and scalability challenges. Jeremy has touched nearly every part of the Pinterest production engineering infrastructure. He currently focuses on reliability engineering for back end data and serving infrastructure.",
    "abstract": "",
    "videos": [],
    "slides": [],
    "hash": "b36d267cfc5245650585eb82b8b29bdb"
  },
  {
    "name": "Chrissie Brodigan",
    "github": "chrissiebrodigan",
    "twitter": "tenaciouscb",
    "bio": "Chrissie leads user experience research for GitHub. She previously worked at Mozilla and with startups designing experiences to help onboard new users. Long before she was a user researcher, she was a historian who studied and wrote about gender and labor with an emphasis on women’s careers in aviation.",
    "abstract": "Measuring Hard to Measure Things",
    "videos": [],
    "slides": [],
    "hash": "f091db85bc34be872c938ba9b0901e60"
  },
  {
    "name": "Roy Rapoport",
    "github": "royrapoport",
    "twitter": "royrapoport",
    "bio": "Roy Rapoport manages the Insight Engineering group at Netflix, responsible for building Netflix's Operational Insight platforms, including cloud telemetry, alerting, and real-time analytics. He originally joined Netflix as part of its datacenter-based IT/Ops group, and prior to transferring over to Product Engineering, was managing Service Delivery for IT/Ops.",
    "abstract": "Operational Insight: Concepts and Real-World Applications",
    "videos": [],
    "slides": [],
    "hash": "419952b0d99c3397799e4dc6a123204f",
  },
  {
    "name": "Laura Thomson",
    "github": "lauraxt",
    "twitter": "lxt",
    "bio": "Laura Thomson is the Director of Engineering, Cloud Services Engineering and Operations at Mozilla, where she leads engineering teams responsible for the development, operations, quality assurance, and security of Mozilla web applications and cloud services. She has been in various engineering roles at Mozilla for the last seven years, and previously worked in jobs including Principal/VP at OmniTI, web developer, consultant, and computer science academic.<br /><br />Nagios sends her more email than her friends do, and she spends more time looking at graphs than pictures of her family. She has written several books on various Open Source technologies, and is trying to speak at fewer conferences. Laura lives with her family on a rustic horse farm in Maryland, where she relaxes by indulging in manual labor and other rural pursuits.",
    "abstract": "Engineering Happiness",
    "videos": [],
    "slides": [],
    "hash": "fead61362ab9263d8cc3af52bd74168e"
  },
  {
    "name": "Arun Kejariwal",
    "github": "akejariwal",
    "twitter": "arun_kejariwal",
    "bio": "Arun is currently a Capacity and Performance Engineer at Twitter where he works on research and development of novel techniques to improve the accuracy of capacity models and demand forecasts. Prior to joining Twitter, he worked on research and development of practical and statistically rigorous methodologies to deliver high performance, availability and scalability in large scale distributed clusters. Some of the techniques developed have been published in peer-reviewed international conferences/journals. Arun received his Bachelor’s degree in EE from IIT Delhi and doctorate in CS from UCI.",
    "abstract": "Practical and Robust Anomaly Detection",
    "videos": [],
    "slides": [],
    "hash": "c861b4498e2702c3546c9e4251b26c38",
  },
  {
    "name": "Kyle Kingsbury",
    "github": "aphyr",
    "twitter": "aphyr",
    "bio": "Kyle Kingsbury is a software engineer at Stripe, the lead author of the Riemann monitoring system, and principal instigator behind Jepsen: an exploration of distributed systems safety. He's obsessed with Clojure, databases, and networks.",
    "abstract": "Working with Riemann",
    "videos": [],
    "slides": [],
    "hash": "e145b50faf662e70c066b13c98921900"
  },
  {
    "name": "Danielle Sucher",
    "github": "DanielleSucher",
    "twitter": "DanielleSucher",
    "bio": "Danielle is a software engineer at Stripe, where she works on data infrastructure and machine learning. She loves digging into the guts of things and building art and puzzles and tools and toys, because it’s way easier than sitting still.",
    "abstract": "Breaking Production for Fun and Profit: Running Game Days at Stripe",
    "videos": [],
    "slides": [],
    "hash": "dc9f215c22985887d9929b85b02c49ef"
  },
  {
    "name": "Dan Frank",
    "github": "danielhfrank",
    "twitter": "danielhfrank",
    "bio": "Dan works on the data team at Stripe, and previously worked at Bitly and Trendrr. He spends a lot of time on mountains.",
    "abstract": "Breaking Production for Fun and Profit: Running Game Days at Stripe",
    "videos": [],
    "slides": [],
    "hash": "f23de27bf1eaa7e07152ee18b23f2261"
  },
  {
    "name": "Franklin Hu",
    "github": "franklinhu",
    "twitter": "thisisfranklin",
    "bio": "Franklin works on infrastructure at Stripe. Previously, he has worked on Zipkin–a distributed tracing system–and Observability at Twitter. In his free time, he enjoys board games, Broadway music, and the Oxford comma.",
    "abstract": "Breaking Production for Fun and Profit: Running Game Days at Stripe",
    "videos": [],
    "slides": [],
    "hash": "37c3b62c818038a84bef21a78a126eec"
  },
  {
    "name": "Tony Rippy",
    "github": "",
    "twitter": "TonyRippy",
    "bio": "Tony Rippy is a Staff Software Engineer at Google. He currently manages the Production Monitoring SRE team in New York, which is responsible for running a wide variety of systems used internally to watch, measure and analyze the behavior of Google's home-grown software. He has spent the last 10 years focused on the development and operation of large-scale distributed computing infrastructure.",
    "abstract": "The Evolution of Monitoring Systems at Google",
    "videos": [],
    "slides": [],
    "hash": "f807c707da14b2c9d41c2d0738c0470e",
  },
  {
    "name": "Stephen Boak",
    "github": "sboak",
    "twitter": "sboak",
    "bio": "Steve is the CPO and co-founder of Opsee, enabling monitoring-driven development. He’s been a designer in the monitoring world for the last 5 years, and was previously head of product at Opsmatic and lead designer at Boundary. This experience has helped him map the territory of both successful and unsuccessful strategies in designing monitoring products - something he’s looking forward to sharing with you. Steve lives in San Francisco, and you can find him on Twitter <a href=\"https://twitter.com/sboak\">@sboak</a>.",
    "abstract": "I'm a designer and I'm here to help",
    "videos": [],
    "slides": [],
    "hash": "20be221be9bb28194db393512d90b2db",
  },
  {
    "name": "Baron Schwartz",
    "github": "xaprb",
    "twitter": "xaprb",
    "bio": "Baron is the founder and CEO of VividCortex, the best way to see what your production database servers are doing. He is the author of High Performance MySQL and lots of open-source software.",
    "abstract": "Probabilistically Sampling A Stream Of Events With A Sketch",
    "videos": [],
    "slides": [],
    "hash": "977a4ffac5032d87447dac02b9b40620",
  },
  {
    "name": "Preetam Jinka",
    "github": "PreetamJinka",
    "twitter": "preetamjinka",
    "bio": "Preetam is an engineer at VividCortex and an undergraduate math student at the University of Virginia.",
    "abstract": "Probabilistically Sampling A Stream Of Events With A Sketch",
    "videos": [],
    "slides": [],
    "hash": "fbcd67d9de295f5215b20a43daf093ee",
  },
  {
    "name": "James Turnbull",
    "github": "jamtur01",
    "twitter": "kartar",
    "bio": "James Turnbull is the author of seven technical books about open source software, including a book on Docker. James works for Kickstarter as VP of Engineering. He was previously in leadership roles at Docker, Venmo and Puppet Labs. James speaks regularly at conferences including OSCON, Velocity, Linux.conf.au, FOSDEM and a number of others. He is a past president of Linux Australia, a former committee member of Linux Victoria, was Treasurer for LCA 2008, and serves on the program committees of LCA and OSCON.",
    "abstract": "Monitoring As A Service",
    "videos": [],
    "slides": [],
    "hash": "31cc2100279326dd6148a7e163692097",
  },
  {
    "name": "Curt Micol",
    "github": "asenchi",
    "twitter": "asenchi",
    "bio": "Curt Micol is an Operations Engineer at Simple, where they allow him to tinker with their platform and develop new processes around complex incident management. When he's done with work he spends time with family, produces music, studies drumming and plays in a rock band.",
    "abstract": "Incident Management and the Incident Complexity Framework",
    "videos": [],
    "slides": [],
    "hash": "f10fbf2ec03a78d9c178d198d1c48b62",
  },
  {
    "name": "Dave Josephsen",
    "github": "djosephsen",
    "twitter": "davejosephsen",
    "bio": "As the developer evangelist for Librato, Dave Josephsen hacks on tools and documentation, writes about statistics, systems monitoring, alerting, metrics collection and visualization, and generally does anything he can to help engineers and developers close the feedback loop in their systems. He’s written books for Prentice Hall and O’Reilly, speaks shell, Go, C, Python, Perl and a little bit of Spanish (in that order). He has never lost a game of Calvinball.",
    "abstract": "Stream Processing inside Librato",
    "videos": [],
    "slides": [],
    "hash": "7c42f38050f8ef68753c28b00e57f5ae",
  },
  {
    "name": "Andrew Clegg",
    "github": "andrewclegg",
    "twitter": "andrew_clegg",
    "bio": "Andrew joined Etsy in 2014, and lives in London, making him their first data scientist outside the USA. Prior to Etsy he spent almost 15 years designing machine learning workflows, and building search and analytics services, in academia, startups and enterprises, and in an ever-growing list of research areas including biomedical informatics, computational linguistics, social analytics, and educational gaming. These days he’s interested in data visualization, probabilistic algorithms and data structures, deep learning, online learning, and the convergence of search and recommender systems. He can count to over 1000 on his fingers but doesn’t know how to drive a car.",
    "abstract": "",
    "videos": [],
    "slides": [],
    "hash": "d1fa34709e3f874600e4a4321c2b2c89",
  },
  {
    "name": "Benjamin Anderson",
    "github": "banjiewen",
    "twitter": "banjiewen",
    "bio": "Benjamin Anderson is a founder and engineer at Multiset, where he works on everything from sales to Chef. Prior to founding Multiset he led the Service Reliability team at Cloudant, where he built systems and processes to monitor and operate Cloudant’s database-as-a-service offering. He lives in Seattle with his wife, his dog, and his books.",
    "abstract": "Observability, Interactivity and Mental Models in Web Operations",
    "videos": [],
    "slides": [],
    "hash": "7ef94f16d9d6be5639580becd295d677",
  },
  {
    "name": "Loris Degioanni",
    "github": "ldegio",
    "twitter": "lorisdegio",
    "bio": "Loris is the CEO and founder of sysdig, Inc., a San Francisco-based startup specialized in visibility and performance management for cloud infrastructures. Prior to founding Draios, Loris was a senior director of technology at Riverbed Technology, where he oversaw strategic technology roadmaps for the company’s network performance management business unit. Loris joined Riverbed after the acquisition of CACE Technologies, the company behind the Wireshark open source network analyzer that he co-founded in 2005. As CTO of CACE, Loris designed and led the development of the company's award-winning packet capture and network analysis product line. Loris has a long history of contributing to and supporting the open source community. He is the creator of the recently released sysdig, a widely used open source system monitoring and exploration tool. He has also been a pioneer in the field of open source network analysis through his work on WinPcap and Wireshark. These open source tools have millions of users worldwide. Loris holds a PhD in computer engineering from Politecnico di Torino and lives in Davis, California.",
    "abstract": "The Dark Art of Container Monitoring",
    "videos": [],
    "slides": [],
    "hash": "e5b02530c848003d51543e72db84eded",
  },
  {
    "name": "Sergey Fedorov",
    "github": "syfedorov",
    "twitter": "Serginio89",
    "bio": "Sergey is a software engineer at Netflix where he is working on monitoring and data analysis tools for Open Connect CDN, helping to make sure you keep binge watching that TV show. Prior to joining Netflix, Sergey worked at Microsoft on Bing infrastructure and monitoring platforms. Recently he's been obsessed with metrics, python, rich javascript applications and REST APIs. When not around the laptop Sergey can be seen hiking, homebrewing or playing hockey.",
    "abstract": "Monitoring Netflix Content Delivery Network",
    "videos": [],
    "slides": [],
    "hash": "ea81944f0da061e9a58c68041b4ab60f",
  },
  {
    "name": "Rob Miller",
    "github": "rafrombrc",
    "twitter": "n0nsequitarian",
    "bio": "Rob Miller is an engineer on Mozilla's Cloud Services team, where he's been heading up the Heka project since late 2012. Prior to his current stint building data processing pipelines, he mostly wrote open source web software for non-profit and mission-based organizations. He has contributed to widely used Python web frameworks such as Pyramid, Zope, and Plone, and he's put his efforts towards such subversive ends as bringing an open source ethos to the development of civic infrastructure, performing radical social experiments in the Black Rock Desert, researching new energy generation technology, preserving translations of dying languages for posterity, and hosting Chinese language websites for the Dalai Lama.",
    "abstract": "",
    "videos": [],
    "slides": [],
    "hash": "e1a84ff925d8a5df8446dc2c6a106b9c",
  },
  {
    "name": "Jamie Wilkinson",
    "github": "jaqx0r",
    "twitter": "jaqx0r",
    "bio": "Jamie works as a Site Reliability Engineer in Google's storage infrastructure group, primarily on automation and monitoring to improve the lives of his team-mates when oncall.",
    "abstract": "",
    "videos": [],
    "slides": [],
    "hash": "2eef5c2b2706aa8146daaef9a837bb91",
  },
  {
    "name": "Kyle Brandt",
    "github": "kylebrandt",
    "twitter": "kylembrandt",
    "bio": "Kyle Brandt is the co-author of the Bosun monitoring system and the Director of Site Reliability at Stack Exchange (the company behind Stack Overflow). He will talk to you about monitoring until he starts to lose his voice. He also enjoys spending time with his wife and pets (2 cats and a dog), video games, weight lifting, and road trips on his Harley.",
    "abstract": "",
    "videos": [],
    "slides": [],
    "hash": "392ee4063cc5e6cc4d0cdb5f658bcfa8",
  },
  {
    "name": "Gian Merlino",
    "github": "gianm",
    "twitter": "gianmerlino",
    "bio": "Gian is a committer on the Druid project and a senior software engineer at Metamarkets, where he is responsible for the infrastructure behind its data ingestion pipelines. He comes to Metamarkets from Yahoo! where he worked on its worldwide server deployment and configuration management platform. He holds a BS in Computer Science from Caltech.",
    "abstract": "",
    "videos": [],
    "slides": [],
    "hash": "1913a548e9db93a970aef9faca37b339",
  },
  {
    "name": "Pierre-Yves Ritschard",
    "github": "pyr",
    "twitter": "pyr",
    "bio": "Pierre-Yves is CTO at exoscale where he is responsible for architecture and strategic technology choices, relying on experience in the architecture of very large corporate system as well as technical product design in several startups. Pierre-Yves is an active member of the open-source community with key contributions to OpenBSD, collectd and riemann amongst others.",
    "abstract": "",
    "videos": [],
    "slides": [],
    "hash": "2fcc875f98607b3007909fe4be99160d",
  }
  /* {
    "name": "",
    "github": "",
    "twitter": "",
    "bio": "",
    "abstract": "",
    "videos": [],
    "slides": [],
    "hash": "",
  } */
]
