var rawSpeakers = {
  "pdx": [
    {
      "name": "John Allspaw",
      "github": "jallspaw",
      "gitlab": "",
      "twitter": "allspaw",
      "bio": "John Allspaw has worked in software systems engineering and operations for over twenty years in many different environments. John’s publications include the books The Art of Capacity Planning (2009) and Web Operations (2010) as well as the forward to \"The DevOps Handbook.\" His 2009 Velocity talk with Paul Hammond, \"10+ Deploys Per Day: Dev and Ops Cooperation\" helped start the DevOps movement. John served as CTO at Etsy, and holds an MSc in Human Factors and Systems Safety from Lund University.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "393c4d3cf4315a211e04f2a85abe7822"
    },
    {
      "name": "Quintessence Anx",
      "github": "quintessence",
      "gitlab": "",
      "twitter": "QuintessenceAnx",
      "bio": "Quintessence has worked in the IT community for over 10 years, including as a database administrator and a DevOps / Cloud / Infrastructure engineer. She was a core contributor to Stark & Wayne's SHIELD project, which adds backup functionality to Cloud Foundry, as well as a technical reviewer for Learning Go Programming published by Packt Publishing. Currently she is the US Developer Advocate for Logz.io, focusing community engagement related to DevOps. Outside of work she is a leader and co-founder of Inclusive Tech Buffalo to help underrepresented minorities in tech launch careers in development.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "fccb008ca5383fd91f2af2cd729b5f7e",
    },
    {
      "name": "Dave Cadwallader",
      "github": "geekdave",
      "gitlab": "",
      "twitter": "geek_dave",
      "bio": "Dave is a Site Reliability Architect at DNAnexus, where on a daily basis, he enjoys geeking out at the intersection of bioinformatics and cloud computing. Dave lives in Colorado with his wife and two kids, and enjoys hiking and playing the drums.",
      "title": "Explain it Like I’m Five - What I Learned Teaching Observability to My Son",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "0293ac60b3127ed135d1a98619fc5669",
    },
    {
      "name": "David Calavera",
      "github": "calavera",
      "gitlab": "",
      "twitter": "calavera",
      "bio": "David Calavera is the CTO of Netlify where he and his team are building the best platform for deploying and automating modern web projects. Before that, he was a core member of the Docker Engine project, where he helped developers build the container engine that started the container revolution. David also built enterprise tools for GitHub and has contributed to numerous open source projects, such us Go, JRuby and many others.",
      "title": "Observability and performance analysis with BPF",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e4e3786e5f54bdc459764759f021f060",
    },
    {
      "name": "Evan Chan",
      "github": "velvia",
      "gitlab": "",
      "twitter": "Evanfchan",
      "bio": "Evan loves to design, build, and improve bleeding edge distributed data and backend systems using the latest in open source technologies. He is the creator of the FiloDB open-source distributed time-series database, as well as the Spark Job Server. He has led the design and implementation of multiple big data platforms based on Storm, Spark, Kafka, Cassandra, and Scala/Akka, including a columnar real-time distributed query engine. He has been an active contributor to the Apache Spark project, and a two-time Datastax Cassandra MVP. He has built Spark applications since Spark 0.8, Cassandra since 0.6. He is a big believer in GitHub, open source, and meetups, and have given talks at various conferences including Strata, Spark Summit, Cassandra Summit, FOSS4G, and Scala Days. He has a Bachelors and Masters of Electrical Engineering, with distinction, from Stanford University. In his spare time he is a family man, photographer, foodie, avid Oakland Athletics fan, and committed follower of Jesus.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "88a87471099c04e7be3f8e568a41537a",
    },
    {
      "name": "Ross Delinger",
      "github": "rossdylan",
      "gitlab": "",
      "twitter": "helixoide",
      "bio": "Ross is an SRE at Dropbox and leads the Reliability-Frameworks team, which is building a distributed tracing solution. Prior to that Ross worked on a variety of observability and service infrastructure tooling on the Traffic team at Dropbox.",
      "title": "Tracing at Dropbox: A Story of Incremental Improvements",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "dda2fda09676d2f8bee4c6c76e25d5f0",
    },
    {
      "name": "Luke Demi",
      "github": "lukedemi",
      "gitlab": "",
      "twitter": "luke_demi_",
      "bio": "Luke Demi is a Software Engineer at Coinbase. Currently, he's excited about bootstrapping reliability culture, serverless observability, and database storage engines. In his spare time he enjoys weighing out backpacking gear and competing against San Francisco Strava segments.",
      "title": "Logs, metrics, and the evolution of observability at Coinbase",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "c67d16dc7d4be109c23a5babcee5f1d5",
    },
    {
      "name": "Jaana B. Dogan",
      "github": "rakyll",
      "gitlab": "",
      "twitter": "rakyll",
      "bio": "Jaana B. Dogan is working on latency analysis projects at Google. Previously, she worked on the Go project. She has a decade-long experience in building developer platforms and tools.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "5ef6ff454a561e34bebfcaa3ef12a738",
    },
    {
      "name": "Nida Farrukh",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Nida is a Software Engineer with over 9 years of experience at Google in Switzerland. She has extensive experience working with and being on-call for large-scale systems designed to serve hundreds of thousands of user requests per second. Concretely, she has expertise in monitoring and load-testing, and has spearheaded efforts in these areas to make related tools and processes as simple, automatic, and widely-applicable as possible. Nida has a track record of safely executing invasive changes to complex, long-standing systems without compromising service availability.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "c59a0850e6a3134342cc1db31308f82a",
    },
    {
      "name": "Sergey Fedorov",
      "github": "syfedorov",
      "gitlab": "",
      "twitter": "Serginio89",
      "bio": "Sergey is an early member of the Open Connect CDN team at Netflix, which has become one of the biggest providers of content on the Internet. Sergey helped build infrastructure to monitor Netflix's streaming experience. Lately, he has switched focus to client-AWS interactions - making Netflix API requests faster, more reliable, and easier to manage. He keeps learning new things about the impact of network conditions on user experience, request performance, and system architecture. Sergey is also an author and maintainer of FAST.com - one of the most popular Internet speed tests.</br></br>Finding actionable signals in loosely controlled environments is what keeps Sergey awake, much better than caffeine. This might also explain why outside of work Sergey can be seen playing ice hockey, brewing beer, or exploring exotic travel destinations.",
      "title": "What can network teach you about your service?",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "ea81944f0da061e9a58c68041b4ab60f",
    },
    {
      "name": "Liz Fong-Jones",
      "github": "lizthegrey",
      "gitlab": "",
      "twitter": "lizthegrey",
      "bio": "Liz is a developer advocate, labor and ethics organizer, and Site Reliability Engineer (SRE) with 15+ years of experience. She is an advocate at Honeycomb.io for the SRE and Observability communities, and previously was an SRE working on products ranging from the Google Cloud Load Balancer to Google Flights.</br></br>She lives in Brooklyn with her wife, metamours, and a Samoyed/Golden Retriever mix, and in San Francisco and Seattle with her other partners. She plays classical piano, leads an EVE Online alliance, and advocates for transgender rights as a board member of the National Center for Transgender Equality.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "3a97f9de48279f72c0422724024d57b8",
    },
    {
      "name": "Aysylu Greenberg",
      "github": "aysylu",
      "gitlab": "",
      "twitter": "aysylu22",
      "bio": "Aysylu Greenberg is a Sr Software Engineer at Google working on infrastructure. In her spare time, she ponders the design of systems that deal with inaccuracies, enthusiastically reads CS research papers, and dances.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e325101665b04328c842d9bf74490d56",
    },
    {
      "name": "Piotr Holubowicz",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Piotr is a Site Reliability Engineer on the Photos team at Google. He likes to work on monitoring and alerting, and making sure the qps stays high, the errors stay low, and the SLOs are green all around. In his spare time he enjoys traveling and occasional cross country running with a compass and a map.",
      "title": "A story of one SLO",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "297dc6bd8754b5413880207716139436",
    },
    {
      "name": "Kenny Johnston",
      "github": "",
      "gitlab": "kencjohnston",
      "twitter": "kencjohnston",
      "bio": "Kenny started his career in political campaigns before returning to his educational background in computer engineering. He has experience with large open-source initiatives through his time working in the early days of OpenStack for HPE and Rackspace. Kenny product manages devops tools aimed at providing easy operational management of complex systems at GitLab. In his spare time, Kenny enjoys building puzzles with his two young children, playing boardgames with his partner, kicking the soccer ball around and learning new cooking techniques. Here's a link to Kenny's <a href=\"https://gitlab.com/kencjohnston/README/blob/master/README.md\">README</a>.",
      "title": "Automation + Artisanship: the Future of Runbooks",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "d647cfc7bc705c66c02eb7e406ee9e63",
    },
    {
      "name": "Nora Jones",
      "github": "",
      "gitlab": "",
      "twitter": "nora_js",
      "bio": "Nora is a Senior Software Engineer at Netflix and a student of Human Factors and Systems Safety at Lund University. She is passionate about resilient software, people, and the intersection of those two worlds.</br></br>She co-wrote the book on Chaos Engineering with her teammates at Netflix and keynoted AWS re:Invent in 2017 to an audience of over 40,000 people about the technical benefits and business case behind implementing Chaos Engineering.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "134967b8b202a412320747801eacf92f",
    },
    {
      "name": "Dave Josephsen",
      "github": "djosephsen",
      "gitlab": "",
      "twitter": "DaveJosephsen",
      "bio": "Dave is an Observability Engineer at Fastly and was like totally speaking at Monitorama before it was cool.",
      "title": "Schema On Read and the New Logging Way",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "544b820dca6b1b9450e57882cf600c75",
    },
    {
      "name": "Prasad Konduri",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Prasad has been with Capital One for over 2 1/2 years and a leader in Enterprise Observability group at Capital One. His responsibilities include Monitoring Governance effort, building the Governance framework, mobilizing all monitoring data to Data Lake for various consumption purposes (Machine Learning, Visualization, Governance etc.) and managing the Infrastructure Monitoring Platforms.",
      "title": "How Capital One used a Data Driven approach and Governance to improve their observability in the Cloud",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "bfb01caa13143772b4895a4f31729b0f",
    },
    {
      "name": "Ryan Lopopolo",
      "github": "lopopolo",
      "gitlab": "",
      "twitter": "",
      "bio": "Ryan founded and led Stripe's Efficiency Engineering team, which focuses on improving the efficiency and rigor of infrastructure decisions through data, reporting, and tooling. Ryan has worked on ETLs for cost attribution, infrastructure for capacity forecasting, and observability for costs, all to help find areas to optimize Stripe's cloud. These systems provide visibility to engineers, product, and leadership and are used to drive organizational initiatives.",
      "title": "The AWS Billing Machine and Optimizing Cloud Costs",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "22a6a3196f3c0b83c5cb9513be025921",
    },
    {
      "name": "Martin Mao",
      "github": "martin-mao",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "How to get the 30,000 ft view, 1 ft view and everything in between without breaking the bank!",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "",
    },
    {
      "name": "Andrew Newdigate",
      "github": "",
      "gitlab": "andrewn",
      "twitter": "suprememoocow",
      "bio": "Andrew is a staff engineer in the Infrastructure team at GitLab, where he helps keep GitLab.com available, observable and scaling. Before GitLab, he cofounded the developer community site Gitter in 2012, and was CTO there until Gitter's acquisition by GitLab in 2017. After living in London in the UK for 17 years, he recently relocated back to his hometown of Cape Town in South Africa.",
      "title": "Practical anomaly detection using Prometheus",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "30a84ee7025f084bba4102cdc8a24b59",
    },
    {
      "name": "Joe Ross",
      "github": "",
      "gitlab": "",
      "twitter": "robusteza",
      "bio": "Joe is a data scientist at SignalFx, where he focuses on time series problems (anomaly detection, forecasting, correlation) that arise in monitoring. He holds a PhD in mathematics from Columbia University and was a researcher and instructor in pure mathematics, most recently at the University of Southern California. He has nine publications in peer-reviewed mathematics/statistics journals and has given talks about his research at conferences and universities throughout the world.",
      "title": "Statistical aspects of distributed tracing",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "2c45622ba5e0df7c693b15107d1ef3f5",
    },
    {
      "name": "Amit Sheth",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Amit Sheth is a Lead Software Engineer/Product Manager at Capital One. He is currently building products which combine a variety of data sources from different monitoring sources and use machine learning techniques to predict outages and perform root cause analysis for incidents. Previously, he was a Platform Manager and Product Owner of several Enterprise Monitoring and ETL tools at Capital One.</br></br>Amit has a Masters Degree in Electrical Engineering from NJIT, USA.",
      "title": "How Capital One used a Data Driven approach and Governance to improve their observability in the Cloud",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "47c6a8da21329a922181946e0c43f2a8",
    },
    {
      "name": "Matty Stratton",
      "github": "mattstratton",
      "gitlab": "",
      "twitter": "mattstratton",
      "bio": "Matty Stratton is a DevOps Advocate at PagerDuty, where he helps dev and ops teams advance the practice of their craft and become more operationally mature. He collaborates with PagerDuty customers and industry thought leaders in the broader DevOps community, and back when he drove, his license plate actually said \"DevOps\".</br></br>Matty has over 20 years experience in IT operations, ranging from large financial institutions such as JPMorganChase and internet firms, including Apartments.com. He is a sought-after speaker internationally, presenting at Agile, DevOps, and ITSM focused events, including ChefConf, DevOpsDays, Interop, PINK, and others worldwide. Matty is the founder and co-host of the popular Arrested DevOps podcast, as well as a global organizer of the DevOpsDays set of conferences.</br></br>He lives in San Francisco and has three awesome kids, who he loves just a little bit more than he loves Doctor Who. He is currently on a mission to discover the best pho in the world.",
      "title": "Fight, Flight, or Freeze — Releasing Organizational Trauma",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "5a17c32166d243cde4bb4ca2f409f7cf",
    },
    {
      "name": "Tom Wilkie",
      "github": "tomwilkie",
      "gitlab": "",
      "twitter": "tom_wilkie",
      "bio": "Tom is a software engineer, Prometheus and Cortex maintainer and VP Product at Grafana Labs. Previous Tom founded Kausal, a company working on Prometheus, and worked at companies such as Weaveworks, Google, Acunu and XenSource. In his spare time, Tom likes to make craft beer and build 3D printers.",
      "title": "Grafana Loki: like Prometheus, but for logs",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "ca56982edb5233cc2f1342ceced2ae43",
    },
    {
      "name": "Christine Yen",
      "github": "christineyen",
      "gitlab": "",
      "twitter": "cyen",
      "bio": "Christine Yen is the cofounder of Honeycomb, a startup with a new approach to observability and debugging systems with data. Christine has built systems and products at companies large and small and likes to have her fingers in as many pies as possible. Previously, she built Parse’s analytics product (and leveraged Facebook’s data systems to expand it) and wrote software at a few now-defunct startups.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "c3c49a4d98ec763dc0f3e559bd4baacd",
    },
  ],
  "baltimore": []
}
