var rawSpeakers = {
  "pdx": [
    {
      "name": "Connie-Lynne Villani",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "With degrees in both Electrical Engineering and Theater Management, Connie-Lynne brings 30 years of System Engineering experience to the table, as well as a keen understanding of how to handle drama in the workplace. In addition to founding and managing Fastly's incident management team, Connie-Lynne has worked at Linden Lab, Change.org, and Groupon, but admits that her favorite position was serving as a board member for the Grilled Cheese Invitational, an annual food festival celebrating all things cheesy.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "8215ce26449737a78a426be0738236e6"
    },
    {
      "name": "Amy Nguyen",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Amy Nguyen is a software engineer working at Stripe and living in Singapore. Today, she works on a core product team building the next generation of payments APIs. Before that, she worked on the observability teams at both Stripe and Pinterest, and spoke at Monitorama 2017 about the user experience of metrics visualization tools. When she's not evangelizing the importance of applying the product mindset to infrastructure engineering, she can be found studying foreign languages, doing yoga, traveling around Southeast Asia, or, most likely of all, drafting jokes for Twitter.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e03c6cfb518abdee5a59561a94b1d34a"
    },
    {
      "name": "Alaina Valenzuela",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Alaina is a software engineer at Honeycomb who has dabbled across the stack enough to know that CSS is way scarier than Ops. Before making the transition into tech, she was a marine biologist studying pinnipeds and birds. When she's not coding she volunteers for the SF Latino Film Festival.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Alyson van Hardenberg",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Alyson is a software engineer at Honeycomb with enthusiasm for charts and data visualizations. In her previous work, she has been everything from a registered nurse, to a customs officer, to working with kids with special needs. If you can think of a job, she's probably done it. She can often be found chasing her two little boys around, baking sourdough, or playing board games.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "5e8e982c69cb6203f161aa9b5f50309c"
    },
    {
      "name": "Joy Scharmen",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Joy fell into a computer career 20+ years ago, and still loves to learn, tinker, and build things. She particularly enjoys building infrastructure focused teams and working across organizations to spread knowledge and understanding. Right now she's in startup life at High Fidelity and is having fun making new things work!",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "8cec5a7ca030ed6c622d44b7b468cd9b"
    },
    {
      "name": "Jonathan Perry",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Jonathan Perry was founder and CEO of Flowmill (now Splunk Network Performance Monitoring), an eBPF-based cloud network observability system. Network observability requires collecting, enriching, and analyzing massive amounts of telemetry; Jonathan takes joy in applying his research and expertise to solve practical day-to-day problems faced by infrastructure SREs - to help observe and address the impact of network communication on distributed services.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6a10a31456d47638485a415243938c5e"
    },
    {
      "name": "Liran Haimovitch",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Liran is the Co-Founder and CTO of Rookout. He’s an advocate of modern software methodologies like agile, lean and devops. Liran’s passion is to understand how software actually works. When he’s not thinking of code, he’s usually diving or hiking.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "dcc2960eb69a643c9a861e3b82a8c4e6"
    },
    {
      "name": "Edward Welch",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Edward has worked a varied history of software development including robotic control systems, vehicle fleet tracking, and telecom middleware. He has worked in both startups and large enterprises, and now finds himself at Grafana Labs where he leads the Loki project, an open source logs aggregation system inspired by Prometheus.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "51fc6152ed93ee0c081860bebfb0738d"
    },
    {
      "name": "Alex Hidalgo",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Alex Hidalgo is a Site Reliability Engineer and author of the upcoming Implementing Service Level Objectives (O'Reilly Media, September 2020). During his career he has developed a deep love for sustainable operations, proper observability, and using SLO data to drive discussions and make decisions. Alex's previous jobs have included IT support, network security, restaurant work, t-shirt design, and hosting game shows at bars. When not sharing his passion for technology with others, you can find him scuba diving or watching college basketball. He lives in Brooklyn with his partner Jen and a rescue dog named Taco. Alex has a BA in philosophy from Virginia Commonwealth University.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "12a5229a997c3322335ce53f2ba6f02d"
    },
    {
      "name": "Uttam Thakore",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Fred Moyer",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Fred is an SRE and the resident SLOgician at Zendesk, where he works to use Error Budgets to deliver best in class reliability for Zendesk's services. Previously he wrangled large scale web systems at Turnitin.com, and earned his Monitoring and Observability wings at Circonus, dealing with large scale time series telemetry implementations. He has two young kids, so he needs more sleep when he's not on the stationary bike in his garage. He likes to hack C, Go, Perl, and Ruby.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6278837dcde59999e3dc77d0beb8a0d1"
    },
    {
      "name": "Owen Diehl",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Owen is informally trained and enjoys self directed learning. He currently works at Grafana on the Cortex & Loki teams, specifically on read path performance. Cortex is a Prometheus compatible backend and Loki is a Prometheus inspired approach to log aggregation. Previously he worked for a small startup, Nutritionix, doing primarily web development. After becoming responsible for both application code and operations, he fell in love with declarative tooling & monitoring. Afterwards, he moved to Fugue in order to marry infrastructure as code and functional programming. In his free time, he plays copious amounts of video games at a low skill level, hikes, and laughs at his own jokes. He is recognizable online by his bulbasaur avatars.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "229e52b0b90630b14f7beb24f4b756d2"
    },
    {
      "name": "Cory Watson",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Cory Watson is a Senior Principal Engineer at Splunk, leading high impact, customer-focused projects around observability and monitoring. Cory started his journey to observability as an SRE at Twitter, and continued on to found the observability team at Stripe. He is a strong voice in the observability community, through OSS, Twitter, blog posts and speaking engagements.</br></br>Cory has over 20 years of software engineering experience, and an active founder / contributor of several successful Open Source projects. Before finding his passion in observability, he worked in several industries such as e-commerce, consulting, healthcare, and fintech.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "cdb8eadd2f62e3eac4db9ea31a4224e3"
    },
    {
      "name": "Hakan Koklu",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Hakan is a Software Engineer in the observability team at Lyft. His main focus is building robust, high scale systems that help Lyft users to go where they need to be. He has worked on data problems as a data analyst, data engineer and software engineer at different companies in the last 6 years. Hakan has a PhD in Electrical Engineering from Boston University focused on optical microscopy and electromagnetic optics. In his spare time, he is trying to read fifty books a year and he fantasizes about learning to play a musical instrument.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "David Wilemski",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "David is a software engineer with over five years of experience developing and operating infrastructure and backend services. He works at Strava on services related to storage and analysis of activities that athletes upload to their Strava profiles. He also helped implement Strava's current monitoring stack. David is interested in distributed systems, infrastructure tools, and how those tools can be improved to make developers more productive. Apart from work, David likes to spend time outside running, camping, and hiking. He's also always up to enjoy a pot of tea with friends.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "d9a24b8fbdb631547adbc78663e144fa"
    },
    {
      "name": "Amber Vaidya",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "I am a Principal Product Manager in the Platform Engineering organization at eBay. We build platforms and services that are used by various other teams at eBay to build experiences for our customers.</br></br>In my current role, I manage the products within the Observability domain. These include products that are used to monitor the health of various layers in our infrastructure ranging from the datacenter and networks all the way to the user-facing experiences.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6fb2b7c7103a6457bc95a11761d6598a"
    },
    {
      "name": "Joe Ross",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Joe Ross holds a PhD in mathematics from Columbia University and was a researcher and instructor in pure mathematics, most recently at the University of Southern California. He has given more than 30 talks about his research at conferences and universities throughout the world, and has 10 publications in peer-reviewed mathematics/statistics journals. Joe has worked as a data scientist at machine learning/analytics startups for six years; in his current role, he focuses on a variety of time series (anomaly detection, forecasting, correlation) and sampling problems that arise in monitoring.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "2c45622ba5e0df7c693b15107d1ef3f5"
    },
    {
      "name": "Anaïs Urlichs",
      "pronouns": "she/her",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Anaïs is a Site Reliability Engineer at Civo, a cloud computing company based on Kubernetes. When she is not advocating DevOps best practices, she runs her own YouTube Channel centered around cloud native technologies. Before transitioning to the cloud native ecosystem, Anaïs helped blockchain projects scale and find adoption. As CNCF ambassador, her passion lies in making tools and platforms more accessible to developers and community members.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "b41e4a33f571fb27346e2e6a2ca6b7c1"
    },
    {
      "name": "Bartek Płotka",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Bartek Plotka is a Principal Software Engineer at Red Hat with a background in SRE, currently working on Observability. As the co-author of the CNCF Thanos project and core maintainer of various open-source projects including Prometheus, he enjoys building OSS communities and maintainable, reliable distributed systems, ideally in Go. On top of that, he is active in the CNCF SIG Observability as the technical lead. He writes a book with O'Reilly.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6d4ebe173fb46263709fc34d4b6eaebc"
    },
    {
      "name": "Adrian Cockcroft",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Adrian Cockcroft has had a long career working at the leading edge of technology, and is fascinated by what happens next. In his new role as VP Sustainability Architecture at Amazon he is developing and sharing best practices for sustainable product architectures, and working with teams across AWS to support their own sustainability programs.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e896a34f14b98f376519b5ed85d1359c"
    },
    {
      "name": "Chris Ward",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Tech writer for Chronosphgere. Podcaster, video maker, writer of interactive fiction & games.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "35a44b69ae5c2c1d250216f8ccc9d67c"
    },
    {
      "name": "Matt Weaver",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Steve Flanders",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "As Engineering Director at Splunk, Steve leads Observability “Getting Data In”: the top contributor to the CNCF OpenTelemetry project. Previously, he served as a founding member and Head of Product at Omnition; and Global Engineering Manager for log analytics at VMware. Steve’s background includes business strategy, software development, product management, user experience, and operations management. He uses data-driven decision-making, agile development processes, and teamwork to create innovative and sustainable solutions; and is distinctly passionate about open-source software and democratizing data. Steve authors SFlanders.net, a technology-centric weblog, and presents regularly at international conferences including KubeCon and Google Cloud Next.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "9c3544f7874a52c775eea8b8f25363d5"
    },
    {
      "name": "Clint Sharp",
      "pronouns": "",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Joe Elliott",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "With degrees in both Electrical Engineering and Theater Management, Connie-Lynne brings 30 years of System Engineering experience to the table, as well as a keen understanding of how to handle drama in the workplace. In addition to founding and managing Fastly's incident management team, Connie-Lynne has worked at Linden Lab, Change.org, and Groupon, but admits that her favorite position was serving as a board member for the Grilled Cheese Invitational, an annual food festival celebrating all things cheesy.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "e04596bcf57f75a82d4c2a2103a0e811"
    },
    {
      "name": "Pete Cheslock",
      "pronouns": "he/him",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "Pete is currently the Chief Product Officer of Allma, helping build the first dynamic workflow management company to help companies solve their most painful and complex events with ease.  Pete is a frequent speaker at Monitorama and loves all things related to monitoring, observability, and metrics.  When he's not helping to build startups, he likes to spend his time fulfilling the requirements of a &quot;suburban dad&quot; by smoking meats and tweeting the results.",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "6f8b01a43eb907d6b473b37724bfc492"
    }
  ],
  "baltimore": [
    /* {
      "name": "Riley Berton",
      "github": "rileyberton",
      "gitlab": "",
      "twitter": "rileyberton",
      "bio": "Riley is a Principal SRE at Major League Baseball with over 20 years experience in building complex systems. He has worked on time series databases @circonus, real time streaming data @AppNexus, audio and video recognition systems @viggle, and audio/video call logging systems @eventide before finding a home at baseball. In his spare time you can find him on the baseball field playing or at the baseball field watching.",
      "title": "What’s Your Service’s Batting Average?",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "64ea38019d0ab54249b9c1d7fa429db1",
    }, */
  ]
}
