var rawSpeakers = {
  "pdx": [
    {
      "name": "Connie-Lynne Villani",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Nikki Attea",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Amy Nguyen",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Alaina Valenzuela",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Alyson van Hardenberg",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Joy Scharmen",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Dr Richard Cook",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Dawn Parzych",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Matt Stratton",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Jonathan Perry",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Liran Haimovitch",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Edward Welch",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Geoffrey Beausire",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Alex Hidalgo",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Dan Slimmon",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Karthik Kambatla",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Fred Moyer",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Furhan Shabir",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Owen Diehl",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Cory Watson",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Hakan Koklu",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Sarah Waldner",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "David Wilemski",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    },
    {
      "name": "Amber Vaidya",
      "github": "",
      "gitlab": "",
      "twitter": "",
      "bio": "",
      "title": "",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": ""
    }
  ],
  "baltimore": [
    /* {
      "name": "Riley Berton",
      "github": "rileyberton",
      "gitlab": "",
      "twitter": "rileyberton",
      "bio": "Riley is a Principal SRE at Major League Baseball with over 20 years experience in building complex systems. He has worked on time series databases @circonus, real time streaming data @AppNexus, audio and video recognition systems @viggle, and audio/video call logging systems @eventide before finding a home at baseball. In his spare time you can find him on the baseball field playing or at the baseball field watching.",
      "title": "What’s Your Service’s Batting Average?",
      "abstract": "",
      "video": "",
      "slides": "",
      "hash": "64ea38019d0ab54249b9c1d7fa429db1",
    }, */
  ]
}
